[package]
name = "raw-speed"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]

[dependencies]
bitflags = "1.2.1"
clap = "2.33.0"
console = "0.10.0"
crossbeam = "0.7.3"
humansize = "1.1.0"
